apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.admission.sysdig.com
spec:
  group: admission.sysdig.com
  version: v1beta1
  groupPriorityMinimum: 10
  versionPriority: 10
  service:
    namespace: default
    name: image-scan-webhook
    port: 8443
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6akNDQWJZQ0NRRHVEcVoxaEhJbk56QU5CZ2txaGtpRzl3MEJBUXNGQURBcE1TY3dKUVlEVlFRRERCNXAKYldGblpTMXpZMkZ1TFhkbFltaHZiMnN1WkdWbVlYVnNkQzV6ZG1Nd0hoY05NakF3TWpBMU1UVXpOalUwV2hjTgpNekF3TWpBeU1UVXpOalUwV2pBcE1TY3dKUVlEVlFRRERCNXBiV0ZuWlMxelkyRnVMWGRsWW1odmIyc3VaR1ZtCllYVnNkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURVUGU3S2JpOUQKcW1COVZSR3loZTF2WWF6bzJYV0VFUnZCS1Rsa3VId3M0T0l2NXJhYllDNHRva21VbnBsYml2ZUplMDJPQ0tSQwpFcGFQQWtCTnZ2UWpETVVxRDJHOG5WaVAzSDFJbnhMeW0wRmxnQVFGOFNrd292ZThHeWJSMkVrd3FJdktDRzJHCmRHcHc3eVRCa2lKQ0hRb0ZvcGlPUzBTb3RRRG5neWNPZkJBSERzb0dEc0ZRb1FuWTFiWFRzazdjTHhqVVE4dHQKSVVPb09CWDluWDB5NXRMREpvcEcydTBSZ0tQRWxUZkQ0MkVwVjZWMFB5eW1waTZPZmlQcitDL2FDU29RN2NPawpESDBkY3RoNHNVWmNWK3NnQUxMdkxwZjl3dlpvbUtzNmY3L3Y1ZUlOT2ExTHR3ZmZpMGZ0L0NpR2FjUVZmb3dDCjJRUHVLSGQ4QjJnUkFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQU1Pc0ZiY0pETk5LWnZHZlVNVlkKUDF1ajVPV0pnY29YTk9GbGVDajhvQkIzOE9PY3FGZUlQVDdpM21mclBQRTMvM0NxTzA5azZWTGFlaVJyQm80UApzSm1Cckt6NmF6Ulh0NXhodTZtamp4d1oxdmplTUFTOFB1dE5Kb0RLNVlmTDk4cnNJclowNnVwazdSbXljYmNTCmh1dkZoeG5tNFdmREtKa0NyYm0zMnR1WERZRVhJckxlQTFIbnFXV0xudWFpLzdzNlVRNE1PRzF6TXZ6eTBMUFkKbDl3Y2d5ZkE3anRKdERyWnFsT1hTajZRK09ZTGxTTjNkNjZyRDRsdzY0a1IzaHloNkdNTCt6N0RGUGxPU21iNQpaclhoallvS2orOVZ3aG1RcFhNZEQ2TGMrcG0wcUFKTDRzcmtUeExQcHhJaXpQR3Q0ZWRvWCtmVXkzMGQrbi8wCnRtVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
