# # Allow delegate authentication and authorization to the service account
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: auth-delegator-image-scan-default
# roleRef:
#   kind: ClusterRole
#   apiGroup: rbac.authorization.k8s.io
#   name: system:auth-delegator
# subjects:
# - kind: ServiceAccount
#   namespace: default
#   name: image-scan-sa
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-delegator-image-scan-admin
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: default
  name: image-scan-sa
# ---
# # to let the admission server read the namespace reservations
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: image-scan-default
# roleRef:
#   kind: ClusterRole
#   apiGroup: rbac.authorization.k8s.io
#   name: image-scan-clusterrole
# subjects:
# - kind: ServiceAccount
#   namespace: default
#   name: image-scan-sa