apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: image-scan-rules
data:
  rules.rego: "package imageadmission\n\nallow_image {\n\tinput.message == \"hello\"\n}\n\nallow_image
    {\n\tinput.ScanReport.Status == \"pass\"\n}\n\ndeny_image[msg] {\n\tnot allow_image\n\tmsg
    := \"Denying images by default\"\n}\n\ndeny_image[msg] {\n\tnot allow_image\n\tmsg
    := \"Because I want to deny\"\n}\n\ndeny_image[msg] {\n\tnot allow_image\n\tmsg
    := input.ScanReport.Status\n}"
