apiVersion: v1
kind: Secret
metadata:
  name: sysdig-secure-token
  namespace: sysdig-image-scan
stringData:
  SYSDIG_SECURE_TOKEN: xxxx
  SYSDIG_SECURE_URL: https://api.sysdigcloud.com/api/scanning/v1/anchore
  