apiVersion: v1
kind: Service
metadata:
  labels:
    app: image-scan-webhook
  name: image-scan-webhook
spec:
  ports:
  - name: webhook-port
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: image-scan-webhook
  sessionAffinity: None
  type: ClusterIP
