apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sysdig-image-scanner.name" . }}-auth-watcher
  namespace: kube-system
  labels:
    {{ include "sysdig-image-scanner.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
    - configmaps
  resourceNames:
  - extension-apiserver-authentication
  verbs:
  - list
  - get
  - watch