apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sysdig-image-scanner.name" . }}-token
  namespace: {{ .Release.namespace }}
  labels:
    {{ include "sysdig-image-scanner.labels" . | nindent 4 }}
stringData:
  SYSDIG_SECURE_TOKEN: {{ .Values.sysdigSecureToken }}